server:
  port: 8090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.6:3306/redpacket?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: mysql.baoning.123456
#redis
  redis:
    host: 192.168.1.6
    port: 6379
    database: 0
    password: redis.baoning.123456

  # kafka
  kafka:
    bootstrap-servers: 192.168.1.6:9092
    producer:
      retries: 0
      batch-size: 1024
      buffer-memory: 1048576
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1

    consumer:
      enable-auto-commit: false
      auto-commit-interval: 100ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 15000
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      resolve-lazily: false

# 配置kafka-topic
kafka:
  topic:
    group-id: redpacket-group
    redpacket-topic: dev_redpacket_topic_statistics


#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xishanqu.redpacket.mapper
