server:
  port: 8090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.6:3306/redpacket?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: mysql.baoning.123456
#redis
  redis:
    host: 192.168.1.6
    port: 6379
    database: 0
    password: redis.baoning.123456
  # kafka
  kafka:
    bootstrap-servers: 192.168.1.6:9092
    producer:
      retries: 0
      batch-size: 1024
      buffer-memory: 1048576
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1

    consumer:
      enable-auto-commit: false
      auto-commit-interval: 100ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 15000
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      resolve-lazily: false
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

# 配置mongodb
  data:
    mongodb:
      host: 192.168.1.6
      port: 27017
      authentication-database: admin
      database: redpacket
      username: admin
      password: mongo.baoning.123456

# 配置session共享
  session:
    store-type: redis

# rabbitmq
  rabbitmq:
    host: 192.168.1.6
    port: 5672
    username: admin
    password: rabbitmq.baoning.123456

# mail
  mail:
    host: smtp.qq.com
    port: 465
    username: captainbn@qq.com
    password: togoumfnzjqncfjf
    default-encoding: UTF-8
    properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    properties.mail.debug: true


# 配置kafka-topic
kafka:
  topic:
    group-id: redpacket-group
    redpacket-topic: dev_redpacket_topic_statistics

# 配置rabbitmq-topic
rabbitmq:
  topic:
    redpacket-topic: prod_redpacket_topic_rabbitmq
  queue:
    redpacket-queue: prod_redpacket_queue_rabbitmq
  routingKey:
    redpacket-routingKey: #.redPacket.#


#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xishanqu.redpacket.mapper
